version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker123:postgres123@db:5432/databaseurl
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2.0' 
          memory: 2G  
        reservations:
          cpus: '1.0' 
          memory: 1G  

  db:
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRES_USER: docker123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: databaseurl
    ports:
      - '5432:5432'
    volumes:
      - postgresql-persistence:/bitnami/postgresql
    deploy:
      resources:
        limits:
          cpus: '1.0' 
          memory: 1G  
        reservations:
          cpus: '0.5' 
          memory: 512M 

volumes:
  postgresql-persistence:
