version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker123:postgres123@db:5432/databaseurl
    depends_on:
      - db

  db:
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRES_USER: docker123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: databaseurl
    ports:
      - '5432:5432'
    volumes:
      - postgresql-persistence:/bitnami/postgresql

  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - '8080:8080'
    depends_on:
      - app
   
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform_container
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace  # Monta o diretório onde o Terraform está configurado
      - ./credentials.json:/workspace/credentials.json  # Monta o arquivo de credenciais
    environment:
      - GOOGLE_PROJECT=${GCP_PROJECT_ID}
      - GOOGLE_CREDENTIALS=/workspace/credentials.json
    entrypoint: /bin/sh -c
    command: >
      terraform init &&
      terraform plan -var="credentials_file_path=/workspace/credentials.json" -var="project_id=${GCP_PROJECT_ID}" -var="region=us-central1"

volumes:
  postgresql-persistence:
