apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "version": 3,
      "name": "API Gateway",
      "port": 8080,
      "endpoints": [
        {
          "endpoint": "/api/v1/urls",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/urls",
              "host": ["http://app:3000"]
            }
          ]
        },
        {
          "endpoint": "/api/v1/auth/login",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/auth/login",
              "host": ["http://app:3000"]
            }
          ]
        }
      ]
    }
