apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: app
        image: 242201286458.dkr.ecr.us-west-2.amazonaws.com/url-shortener:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://docker123:postgres123@db:5432/databaseurl"
      - name: krakend
        image: devopsfaith/krakend
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
