name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create credentials file
      run: echo "${{ secrets.GCP_SA_KEY }}" > ./credentials.json
      shell: bash

    - name: Set up Docker Compose
      run: docker-compose up -d db

    - name: Install dependencies
      run: docker-compose run --rm app npm install

    - name: Run lint
      run: docker-compose run --rm app npm run lint

    - name: Run tests
      run: docker-compose run --rm app npm run test

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose down -v
