name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: docker123
          POSTGRES_PASSWORD: postgres123
          POSTGRES_DB: databaseurl

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - run: npm install
    - run: npm run lint
    - run: npm run test

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Create credentials file
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > ./terraform/credentials.json
        cat ./terraform/credentials.json # Verifica o conteúdo do arquivo
      shell: bash

    - name: Verify credentials file
      run: ls -la ./terraform && cat ./terraform/credentials.json

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var="credentials_file_path=./terraform/credentials.json" -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=us-central1"
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve -var="credentials_file_path=./terraform/credentials.json" -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=us-central1"
      working-directory: ./terraform
